apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: leave-request-system
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: leave-request-config
              key: DATABASE_NAME
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: leave-request-secrets
              key: DATABASE_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: leave-request-secrets
              key: DATABASE_PASSWORD
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-init
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-init
        configMap:
          name: mysql-init-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: leave-request-system
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: leave-request-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: leave-request-system
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS leave_request_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    USE leave_request_db;
    CREATE USER IF NOT EXISTS 'app_user'@'%' IDENTIFIED BY 'app_password';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX ON leave_request_db.* TO 'app_user'@'%';
    FLUSH PRIVILEGES;
    SET time_zone = '+00:00';
