#!/bin/bash

echo "🚀 Starting Leave Request System Backend..."
echo "📋 Configuration Check:"
echo "✅ TypeORM Configuration: Updated to use process.env variables"
echo "✅ Entity Discovery: Using glob pattern *.entity.ts"
echo "✅ ConfigModule: Imported and configured globally"
echo "✅ Environment Variables: Loaded from .env file"
echo ""
echo "📁 Project Structure:"
echo "src/"
echo "├── auth/"
echo "│   ├── auth.module.ts"
echo "│   ├── auth.service.ts" 
echo "│   ├── auth.controller.ts"
echo "│   ├── jwt.strategy.ts"
echo "│   └── jwt-auth.guard.ts"
echo "├── users/"
echo "│   ├── users.module.ts"
echo "│   ├── users.service.ts"
echo "│   ├── users.controller.ts"
echo "│   └── entities/"
echo "│       └── user.entity.ts"
echo "└── app.module.ts (with TypeORM configuration)"
echo ""
echo "🔧 To start the application:"
echo "1. Update .env file with your database credentials"
echo "2. Create MySQL database 'leave_system'"
echo "3. Run: npm run start:dev"
echo ""
echo "📊 Database tables will be automatically created by TypeORM synchronization"
